# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main, v1 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
#  lint:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - uses: actions/cache@v1
#        with:
#          path: ~/.npm
#          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#          restore-keys: |
#            ${{ runner.os }}-node-
#
#      - name: Node 12.16.3
#        uses: actions/setup-node@v1
#        with:
#          node-version: 12.16.3
#
#      - name: NPM install
#        run: npm i
#
#      - name: Run linter
#        run: npm run lint

  deploy:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Node 12.16.3
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.3

      - name: NPM install
        run: npm i

      - name: Angular Production build
        run: |
          npm run build:prod

      - name: Reset Git
        run: git reset --hard

      - name: List output files
        run: ls

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@3.0.0
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}/laravel_sites/themeparks-angular --insecure
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/GameQuest-Player # This folder is NOT going to upload by default unless you add it to .git-ftp-include
